namespace ScenarioBuilder.TestHarness
{
    /// <summary>
    /// Extensions to the <see cref="ScenarioContext"/> class.
    /// </summary>
    internal static class ScenarioContextExtensions
    {
        /// <summary>
        /// Try to get the info generated by an event.
        /// </summary>
        /// <typeparam name="TEventInfo">The type of event info.</typeparam>
        /// <param name="scenarioContext">The context.</param>
        /// <param name="eventInfo">The event info.</param>
        /// <param name="eventIds">The event IDs.</param>
        /// <returns>True if found.</returns>
        internal static bool TryGet<TEventInfo>(this ScenarioContext scenarioContext, out TEventInfo eventInfo, string[] eventIds)
            where TEventInfo : class
        {
            try
            {
                eventInfo = scenarioContext.Get<TEventInfo>(string.Join('_', eventIds));

                return true;
            }
            catch (KeyNotFoundException)
            {
                eventInfo = null!;

                return false;
            }
        }
    }
}
